defaults: &defaults
  host: <%= GlobalSetting.redis_host %>
  port: <%= GlobalSetting.redis_port %>
  password: <%= GlobalSetting.redis_password %>
  db: <%= GlobalSetting.redis_db %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  host: <%= ENV['DISCOURSE_REDIS_HOST'] || GlobalSetting.redis_host %>
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
